# Generated by Django 2.0.7 on 2018-07-09 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField()),
                ('lock', models.BooleanField(db_index=True, default=False)),
                ('priority', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('priority', models.BooleanField(default=False)),
                ('lifo', models.BooleanField(default=False)),
                ('backoff_max', models.FloatField(blank=True, default=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mq.Queue'),
        ),
    ]
